apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-test-app
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: my-test-app
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90